import Head from 'next/head';
import { Ubuntu_Mono } from 'next/font/google';
import GameAdmin from './GameAdmin';

const ubuntuMono = Ubuntu_Mono({ subsets: ['latin'], weight: '400', variable: '--font-ubuntu-mono', display: 'swap' });

export default function Home() {
  return (
    <>
      <Head>
        <title>Connect Four</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={ubuntuMono.variable}>
        <GameAdmin />
      </main>
    </>
  );
}
